name: Build Docker for packaging

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Reclaim disk space
      run: |
        df -h
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/.ghcup
        df -h
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.MLCAI_DOCKERHUB_USERNAME }}
        password: ${{ secrets.MLCAI_DOCKERHUB_TOKEN }}
    - name: Docker CPU
      run: |
        cd docker-cd
        docker build -t package-cpu -f Dockerfile.cpu .
    - name: Docker CUDA 11.7
      run: |
        cd docker-cd
        docker build --build-arg CUDA_NAME_PGK="cuda-11-7" --build-arg CUDA_NAME_TXT="cuda11.7" -t package-cu117 -f Dockerfile.cuda .
    - name: Docker CUDA 11.8
      run: |
        cd docker-cd
        docker build --build-arg CUDA_NAME_PGK="cuda-11-8" --build-arg CUDA_NAME_TXT="cuda11.8" -t package-cu118 -f Dockerfile.cuda .
    - name: Docker CUDA 12.1
      run: |
        cd docker-cd
        docker build --build-arg CUDA_NAME_PGK="cuda-12-1" --build-arg CUDA_NAME_TXT="cuda12.1" -t package-cu121 -f Dockerfile.cuda .
    - name: Docker CUDA 12.2
      run: |
        cd docker-cd
        docker build --build-arg CUDA_NAME_PGK="cuda-12-2" --build-arg CUDA_NAME_TXT="cuda12.2" -t package-cu122 -f Dockerfile.cuda .
    - name: Docker ROCm 5.6
      run: |
        cd docker-cd
        docker build --build-arg ROCM_VER="5.6" -t package-rocm56 -f Dockerfile.rocm .
    - name: Docker ROCm 5.7
      run: |
        cd docker-cd
        docker build --build-arg ROCM_VER="5.7" -t package-rocm57 -f Dockerfile.rocm .
    - name: Upload to Docker Hub
      run: |
        set -eux
        TAG=$(git log -1 --format='%h')
        cd docker-cd
        bash scripts/docker-push.sh $TAG "cpu"
        bash scripts/docker-push.sh $TAG "cu117"
        bash scripts/docker-push.sh $TAG "cu118"
        bash scripts/docker-push.sh $TAG "cu121"
        bash scripts/docker-push.sh $TAG "cu122"
        bash scripts/docker-push.sh $TAG "rocm56"
        bash scripts/docker-push.sh $TAG "rocm57"
